sonar:
  url: https://sonarcloud.io/api
  fetch-interval-cron: 1h
  username-or-token: ""
quarkus:
  application:
    name: Quality Owl
  rest-client:
    sonar:
      url: ${sonar.url}
  banner:
    path: banner.txt
"%dev":
  quarkus:
    log:
      console:
        json: false
"%test":
  quarkus:
    log:
      console:
        json: false
