quarkus:
  application:
    name: Quality Owl
  rest-client:
    sonar:
      url: https://sonarcloud.io/api
"%dev":
  quarkus:
    log:
      console:
        json: false
"%test":
  quarkus:
    log:
      console:
        json: false
