sonar:
  url: https://sonarcloud.io/api
  fetch-interval-cron: 1m
  username-or-token:
  password:
  project-includes:
    - marmer_code-brunch-calc
    - io.github.marmer.testutils:hamcrest-matcher-generator
  metric-keys:
    - bugs
    - code_smells
    - vulnerabilities
    - security_hotspots
    - coverage
    - duplicated_lines_density
    - sqale_index #Technical Dept. Use for Comparison! ;)
quality-owl:
  output-dir: ./target/persistence
quarkus:
  application:
    name: Quality Owl
  rest-client:
    sonar:
      url: ${sonar.url}
  banner:
    path: banner.txt
"%dev":
  quarkus:
    log:
      console:
        json: false
"%test":
  sonar:
    fetch-interval-cron: disabled
  quarkus:
    log:
      console:
        json: false
